[environments.default]
url="jdbc:sqlite:/flyway/db/coffee.db"
user="flyway"
password="password"
cleanDisabled="false"

[flyway]
environment = "default"
locations=["filesystem:sql"]
cleanDisabled="false"
